### ISSUE TITLE
More info for observation needed

### ISSUE THREAD

**Issue by nfkok** [koulanurag/ma-gym#11]
Hi, not really an issue found but I hope I can get answers to my question. 

Taking PongDuel-v0 as example, the observation returns a 2-D list. 
obs=[[0.625, 0.03333, 0.5, 0.3333, 0, 0, 0, 1, 0, 0], [0.625, 0.9333, 0.325, 0.6, 0, 0, 0, 1, 0, 0]]

According to the wiki, it is the agent coordinate and ball location. Are both agent coordinates represented in obs[0] and ball coordinate is represented in obs[1]? May I know how are they being represented using the arrays with size 10?  

Thanks.

**Comment by koulanurag** [comment]
Hi @nfkok ,
It should be this way:
Obs[0] => Observation for Agent 1 =>  agent pos.(2), ball pos. (2), ball-direction (6-onehot)
Obs[1] => Observation for Agent 2 = > agent pos.(2), ball pos. (2), ball-direction (6-onehot)

I guess, following code reference may help you:
- https://github.com/koulanurag/ma-gym/blob/master/ma_gym/envs/pong_duel/pong_duel.py#L36
- https://github.com/koulanurag/ma-gym/blob/master/ma_gym/envs/pong_duel/pong_duel.py#L83
- https://github.com/koulanurag/ma-gym/blob/master/ma_gym/envs/pong_duel/pong_duel.py#L283


Also, This means ball pos. and ball-direction should be same in both the observations which doesn't seems to be the case from your example. And, if it's the case, then , It could be a potential bug and would have to be investigated.

In order to verify , I just ran a quick sample of random actions and it looks that the ball pos. and ball ball direction are same in both the observations.

```bash
>>> import gym
>>> import ma_gym
>>> env = gym.make('PongDuel-v0')
>>> env.reset()
[[0.7, 0.03333333333333333, 0.25, 0.6, 0, 0, 0, 1, 0, 0], [0.125, 0.9333333333333333, 0.25, 0.6, 0, 0, 0, 1, 0, 0]]
>>> env.step(env.action_space.sample())
([[0.675, 0.03333333333333333, 0.275, 0.6333333333333333, 0, 0, 0, 1, 0, 0], [0.1, 0.9333333333333333, 0.275, 0.6333333333333333, 0, 0, 0, 1, 0, 0]], [0, 0], [False, False], {'rounds': 0})
>>> env.step(env.action_space.sample())
([[0.675, 0.03333333333333333, 0.275, 0.6333333333333333, 0, 0, 0, 1, 0, 0], [0.1, 0.9333333333333333, 0.275, 0.6333333333333333, 0, 0, 0, 1, 0, 0]], [0, 0], [False, False], {'rounds': 0})
>>> env.step(env.action_space.sample())
([[0.65, 0.03333333333333333, 0.3, 0.6666666666666666, 0, 0, 0, 1, 0, 0], [0.1, 0.9333333333333333, 0.3, 0.6666666666666666, 0, 0, 0, 1, 0, 0]], [0, 0], [False, False], {'rounds': 0})

```
