### ISSUE TITLE
the state is not match with the picture?

### ISSUE THREAD

**Issue by bradley-code-again** [koulanurag/ma-gym#38]
From the picture of switch2, row3 and column2 is accessable, while when I run the programme, the agent can't reach here?

**Comment by koulanurag** [comment]
Hi @bradley-code-again,

Thanks for raising the issue.  I tried to replicate the mentioned issue and it seems to work correctly. I am sharing the following snippet to replicate the expected behavior.

```
>>> import gym
>>> env = gym.make('ma_gym:Switch2-v0')
>>>  env = Monitor(env, directory='recordings',video_callable=lambda episode_id: True)
>>> env.reset()
[[0.0, 0.17], [0.0, 0.83]]
>>> env.render()
True
>>> env.step([0,0])
([[0.5, 0.17], [0.5, 0.83]], [-0.1, -0.1], [False, False], {})
>>> env.render()
True
>>> env.step([0,0])
([[1.0, 0.17], [1.0, 0.83]], [-0.1, -0.1], [False, False], {})
>>> env.render()
True
>>> env.step([1,1])
([[1.0, 0.0], [1.0, 0.83]], [-0.1, -0.1], [False, False], {})
>>> env.render()
True
>>> env.close()
```

Here's a video of it:
https://user-images.githubusercontent.com/4881224/130829204-6d993fd5-bf8c-4d57-a46f-03368081c36d.mp4

Please, let me know if I have misunderstood the issue.  Also, It will be helpful if you can share a code-snippet to replicate the issue as well as ensure that you have the latest version of ma-gym.
